.TH partial.utf8 5 "October 2001" PARTIAL.UTF8 "Kiwi reference manual"
.SH NAME
.B partial.utf8
- List of iso 8859-1 and utf8 codes for some characters
.SH "THE LIST"
.ta +5 +7 +7
	Letter	8859-1	UTF-8
.br
	¡	0xa1	0xc2a1
.br
	«	0xab	0xc2ab
.br
	»	0xbb	0xc2bb
.br
	¿	0xbf	0xc2bf
.br
	Á	0xc1	0xc381
.br
	É	0xc9	0xc389
.br
	Í	0xcd	0xc38d
.br
	Ñ	0xd1	0xc391
.br	
	Ó	0xd3	0xc393
.br
	Ú	0xda	0xc39a
.br
	á	0xe1	0xc3a1
.br
	é	0xe9	0xc3a9
.br
	í	0xed	0xc3ad
.br
	ñ	0xf1	0xc3b1
.br
	ó	0xf3	0xc3b3
.br
	ú	0xfa	0xc3ba

.SH AUTHOR
Sam Trenholme <kiwi-zttfryb@koala.samiam.org>
